export const messageResponseError = {
  auth: {
    phoneOrPasswordWrong: "phone_or_password_wrong",
    phoneAlreadyExists: "phone_already_exists",
    otpExpired: "otp_expired",
    otpLimitExceeded: "otp_limit_exceeded",
    userNotFound: "user_not_found",
    otpInvalid: "otp_invalid",
    otpAlreadySent: "otp_already_sent",
    userNameAlreadyExists: "user_name_already_exists",
    refreshTokenInvalid: "refresh_token_invalid",
    refreshTokenExpired: "refresh_token_expired",
    phoneAlreadyExistsOrNotMatch: "phone_already_exists_or_not_match",
    stepInvalid: "step_invalid",
    passwordInvalid: "password_invalid",
    referralCodeNotFound: "referral_code_not_found",
    actionInvalid: "action_invalid",
  },
  wallet: {
    customerNotFound: "customer_not_found",
    insufficientBalance: "insufficient_balance",
    notFound: "wallet_not_found",
    accessCodeInvalid: "access_code_invalid",
    accessCodeExpired: "access_code_expired",
    partnerNotFound: "partner_not_found",
    actionInvalid: "wallet_action_invalid",
    notEnoughBalance: "not_enough_balance",
  },
  blog: {
    notFound: "blog_not_found",
    duplicate: "blog_duplicate",
    missingDataRedirect: "missing_data_redirect",
    missingDataScreen: "missing_data_screen",
  },
  blogCate: {
    notFound: "blog_category_not_found",
    duplicate: "blog_category_duplicate",
  },
  voucher: {
    discountThan0: "discount_than_0",
    voucherNotFound: "voucher_not_found",
    voucherAlreadyExits: "voucher_already_exists",
    cannotDeleteBecauseUsed: "cannot_delete_because_used",
    voucherExpired: "voucher_expired",
    voucherOutOfStock: "voucher_out_of_stock",
    voucherAlreadyUsed: "voucher_already_used",
    voucherTypeInvalid: "voucher_type_invalid",
    voucherPaymentMethodInvalid: "voucher_payment_method_invalid",
    voucherNotStarted: "voucher_not_started",
    voucherMinimumOrderNotReached: "voucher_minimum_order_not_reached",
  },
  admin: {
    passSame: "password_same",
    notFound: "admin_not_found",
    passInvalid: "password_invalid",
    noChanges: "no_changes",
    lastAdminCannotDelete: "last_admin_cannot_delete",
    userNameOrPasswordWrong: "user_name_or_password_wrong",
    userNameAlreadyExists: "user_name_already_exists",
    actionInvalid: "action_invalid",
  },
  customer: {
    notFound: "customer_not_found",
    actionInvalid: "action_invalid",
    phoneAlreadyExists: "phone_already_exists",
    passwordRequired: "password_required",
    passwordSame: "password_same",
    invalidPassword: "invalid_password",
  },
  partner: {
    notFound: "partner_not_found",
    actionInvalid: "action_invalid",
    phoneAlreadyExists: "phone_already_exists",
    passwordRequired: "password_required",
    passwordSame: "password_same",
    invalidPassword: "invalid_password",
    statusNotActive: "partner_status_not_active",
    invalidLocation: "invalid_location",
    invalidOperatingHours: "invalid_operating_hours",
    typeChangeNotAllowed: "partner_type_change_not_allowed",
  },
  upload: {
    fileInvalid: "file_invalid",
  },
  transaction: {
    notFound: "transaction_not_found",
    actionInvalid: "transaction_action_invalid",
    sourceInvalid: "transaction_source_invalid",
    withdrawNotAllowed: "transaction_withdraw_not_allowed",
    refundNotAllowed: "transaction_refund_not_allowed",
    evidenceAlreadyExists: "evidence_already_exists",
  },
  config: {
    notFound: "config_not_found",
    keyExists: "config_key_exists",
  },
  permission: {
    // Action errors
    actionNotFound: "action_not_found",
    actionDuplicate: "action_duplicate",
    actionInUse: "action_in_use",

    // System Action errors
    sysPermissionNotFound: "sys_permission_not_found",
    sysPermissionDuplicate: "sys_permission_duplicate",
    sysPermissionInUse: "sys_permission_in_use",

    // Group Role errors
    groupRoleNotFound: "group_role_not_found",
    groupRoleDuplicate: "group_role_duplicate",
    groupRoleInUse: "group_role_in_use",

    // System Action Action errors
    sysPermissionActionNotFound: "sys_permission_action_not_found",
    sysPermissionActionDuplicate: "sys_permission_action_duplicate",

    // Group Role Action errors
    groupRolePermissionNotFound: "group_role_permission_not_found",
    groupRolePermissionDuplicate: "group_role_permission_duplicate",
  },
  user: {
    notFound: "user_not_found",
  },
  address: {
    notFound: "address_not_found",
    actionInvalid: "address_action_invalid",
    defaultAddressExists: "default_address_exists",
    pickupAddressExists: "pickup_address_exists",
    returnAddressExists: "return_address_exists",
  },
  notification: {
    notFound: "notification_not_found",
  },
  shoeService: {
    customerIdNotAllowed: "customer_id_not_allowed",
    notFound: "shoe_service_not_found",
    duplicateName: "shoe_service_duplicate_name",
  },
  shoeBooking: {
    notFound: "shoe_booking_not_found",
    actionInvalid: "shoe_booking_action_invalid",
    bookingDateTooClose: "booking_date_too_close",
    pickupAddressRequired: "pickup_address_required",
    deliveryAddressRequired: "delivery_address_required",
    returnAddressRequired: "return_address_required",
    shoeServiceNotFound: "shoe_service_not_found",
    imageUrlsInvalid: "image_urls_invalid",
    originalPriceAndShoeServiceDesRequired: "original_price_and_shoe_service_description_required",
    accessCodeNotAllowed: "access_code_not_allowed",
    notPendingPayment: "shoe_booking_not_pending_payment",
  },
};
