export * from './action.repository';
export * from './address.repository';
export * from './admin.repository';
export * from './customer.repository';
export * from './group_role.repository';
export * from './group_role_permission.repository';
export * from './partner.repository';
export * from './sys_permission.repository';
export * from './sys_permission_action.repository';