export enum UserStatusEnum {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum StatusBlogEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum CarpoolBookingStatusEnum {
  PENDING = 'PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  FIND_DRIVER = 'FIND_DRIVER',
  DRIVER_ACCEPTED = 'DRIVER_ACCEPTED',
  WAITING = 'WAITING',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_PAYMENT_COMPLETION = 'PENDING_PAYMENT_COMPLETION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  WAITING_DRIVER_ACCEPT = 'WAITING_DRIVER_ACCEPT',
}

export enum CarRegistryStatusEnum {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
}

export enum TripStatusEnum {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum DeliveryStatusEnum {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  FIND_DRIVER = 'FIND_DRIVER',
  DRIVER_ACCEPTED = 'DRIVER_ACCEPTED',
  WAITING = 'WAITING',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  WAITING_DRIVER_ACCEPT = 'WAITING_DRIVER_ACCEPT',
}

export enum CarrierCodeHistoryEnum {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum VehicleBookingStatusEnum {
  PENDING_CODE = 'PENDING_CODE',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  FIND_DRIVER = 'FIND_DRIVER',
  WAITING = 'WAITING',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_PAYMENT_COMPLETION = 'PENDING_PAYMENT_COMPLETION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}