export enum StepEnum {
  OTP = 'OTP',
  NEW_PASSWORD = 'NEW_PASSWORD',
  REGISTER_INFO = 'REGISTER_INFO',
  REGISTER_SOCIAL_MEDIA = 'REGISTER_SOCIAL_MEDIA',
  REGISTER_INFO_SUCCESS = 'REGISTER_INFO_SUCCESS',
  COMPLETED = 'COMPLETED',
}
